# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
    ]
