# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-14 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrainer', '0005_buy_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_annual_eps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_annual_net_income',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_annual_revenue',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_annual_total_assets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='stock',
            name='website',
            field=models.CharField(default='', max_length=500),
        ),
    ]
